---
- hosts: rhel`
  name: Run a script on remote hosts
  gather_facts: no

  vars: 
    cent_hosts: [ '1cent', '2cent' ]

  tasks:
    - name: Execute the script
      shell:
        "/home/adrian/{ cent_hosts }_script.sh"
