---
- hosts: rhel
  name: Run a script on remote hosts
  gather_facts: yes

  tasks:
    - name: Execute the script
      shell: |
        "/home/adrian/{{ ansible_hostname }}_script.sh"
        
        expect "Enter a password"
        send "{{ sample_pass }}\n"

      args:
        executable: /usr/bin/expect
      vars:
        sample_pass: "somepassw0rd"    
